[package]
name = "nix-for-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
bindgen = "0.69.4"
pkg-config = "0.3.30"

[dependencies]
anyhow = "1.0.83"
home = "0.5.9"
thiserror = "1.0.60"
