[package]
name = "mx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = [ "derive" ]}
nix-for-rust = { path = "../nix-for-rust", features = ["eval-cache"] }
serde = "1.0.216"
serde_json = "1.0.133"
tempdir = "0.3.7"
